### PR TITLE
Pass context to api calls

### PR DESCRIPTION
**Pull request by k-yomo**
This PR refactors methods to pass context to api calls to be context aware.

### CODE REVIEW

**Comment by tobio** [comment]
@k-yomo are you able to add a changelog entry here?

**Comment by k-yomo** [comment]
@tobio 
I added to changelog!  Also fixed missing parameter error🙏

**Comment by tobio** [comment]
jenkins test this

**Review by tobio — APPROVED** [review]
Thanks for this! I'll look at shipping a release this week, there's some useful changes in the unreleased set here.

**Pull request merged**
