### PR TITLE
Fix not found handling for snapshot repository

### PR DESCRIPTION
**Pull request by k-yomo**

### CODE REVIEW

**Review by tobio — COMMENTED** [review]
Can we add a changelog entry here.

**Review by tobio — DISMISSED** [review]

**Comment by tobio** [comment]
jenkins test this

**Comment by k-yomo** [comment]
@tobio 
Sorry, it was conflicting with the other PR just merged, could you re-run the jenkins?🙏

**Comment by tobio** [comment]
jenkins test this

**Review by tobio — APPROVED** [review]

**Pull request merged**
