### PR TITLE
Fix fleet resources not having ID set on import

### LINKED ISSUE #369: [Bug] Cannot import Fleet output
**Describe the bug**
I am trying to import an `elasticstack_fleet_output` which always fails and I do not have any idea what I am doing wrong. According to the docs, it is as simple as configuring the kibana connection and executing `terraform import elasticstack_fleet_output.my_output <space id>/<output id>`

**To Reproduce**
My Connection config is:
```terraform
provider "elasticstack" {
  elasticsearch {
    username  = "elastic"
    password  = ""
    endpoints = "https://elastichost:9200"
    ca_file   = "./certs/root.crt"
  }
  kibana {
    username  = "elastic"
    password  = ""
    endpoints = "https://elastichost:5601"
    insecure = true
  }
  fleet {
    username = "elastic"
    password = ""
    endpoint = "https://elastichost:8220"
    ca_certs = ["./certs/root.crt", "./certs/intermediate.crt"]
  }
}
```

My output config is:
```terraform
resource "elasticstack_fleet_output" "default_output" {
  name = "default"
  type = "elasticsearch"
  default_integrations = true
  default_monitoring   = true
  hosts                =  ["https://elastichost:9200"]
}
```

**Expected behavior**
I would expect that the output is successfully imported.

**Debug output**
When running `terraform import -var-file="test.tfvars" elasticstack_fleet_output.default_output default/fleet-default-output`, I get the following HTTP404 error:
> 2023-06-27T09:46:46.963+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.6.2.exe: Fleet API Request Details:
---[ REQUEST ]---------------------------------------
GET /api/fleet/outputs/ HTTP/1.1
Host: elastichost:8220
User-Agent: Go-http-client/1.1
Authorization: ***********************************************
Accept-Encoding: gzip
> 2023-06-27T09:46:47.028+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.6.2.exe: Fleet API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Tue, 27 Jun 2023 07:46:47 GMT
X-Content-Type-Options: nosniff
>
>404 page not found

I don't know why the provider tried to connect to the fleet server when the docs say that Kibana is required, so I temporarily removed the fleet server. After this, I get:
> 2023-06-27T10:02:06.627+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.6.2.exe: Fleet API Request Details:
---[ REQUEST ]---------------------------------------
GET /api/fleet/outputs/ HTTP/1.1
Host: elastichost:5601
User-Agent: Go-http-client/1.1
Authorization: ***********************************************
Accept-Encoding: gzip
> 2023-06-27T10:02:06.708+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.6.2.exe: Fleet API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 302 Found
Cache-Control: private, no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Security-Policy: script-src 'self'; worker-src blob: 'self'; style-src 'unsafe-inline' 'self'
Cross-Origin-Opener-Policy: same-origin
Date: Tue, 27 Jun 2023 08:02:06 GMT
Kbn-License-Sig: 03419a885e4908987730578d44854c956b83a3a5e2eba9735cf01d5f98c1f99b
Kbn-Name: elastic-q
Keep-Alive: timeout=120
Location: /api%2Ffleet%2Foutputs
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Content-Length: 0
> 2023-06-27T10:02:06.708+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.6.2.exe: Fleet API Request Details:
---[ REQUEST ]---------------------------------------
GET /api%2Ffleet%2Foutputs HTTP/1.1
Host: elastichost:5601
User-Agent: Go-http-client/1.1
Authorization: ***********************************************
Referer: https://elastichost:5601/api/fleet/outputs/
Accept-Encoding: gzip
> 2023-06-27T10:02:06.735+0200 [DEBUG] provider.terraform-provider-elasticstack_v0.6.2.exe: Fleet API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Content-Length: 60
Cache-Control: private, no-cache, no-store, must-revalidate
Connection: keep-alive
Content-Security-Policy: script-src 'self'; worker-src blob: 'self'; style-src 'unsafe-inline' 'self'
Content-Type: application/json; charset=utf-8
Cross-Origin-Opener-Policy: same-origin
Date: Tue, 27 Jun 2023 08:02:06 GMT
Kbn-License-Sig: 03419a885e4908987730578d44854c956b83a3a5e2eba9735cf01d5f98c1f99b
Kbn-Name: elastic-q
Keep-Alive: timeout=120
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
>
>{
 "statusCode": 404,
 "error": "Not Found",
 "message": "Not Found"
}

Maybe, only the trailing slash is wrong? The same call fails in Kibana DevTools:
`GET kbn:api/fleet/outputs/`
But this succeeds:
`GET kbn:api/fleet/outputs`

**Versions (please complete the following information):**
 - OS: [e.g. Linux] Terraform - Windows, Elastic Stack - Linux
 - Terraform Version 1.5.0
 - Provider version 0.6.2
 - Elasticsearch Version 8.7.0

### LINKED ISSUE #396: [Bug] Cannot import Fleet policy
## Describe the bug

I am trying to import an `elasticstack_fleet_agent_policy` using the instructions in the [documentation](https://registry.terraform.io/providers/elastic/elasticstack/latest/docs/resources/fleet_agent_policy#import), which states:

> Import is supported using the following syntax:
> ```
> terraform import elasticstack_kibana_fleet_agent_policy.my_policy <space id>/<policy id>
> ```

I get the following error:

```
Error: Cannot import non-existent remote object
 
While attempting to import an existing object to "module.fleet.elasticstack_fleet_agent_policy.fleet_policy[\"test-policy\"]", the provider detected that no object exists with the
given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to
create a new remote object for this resource.
```

This is the same behavior reported in Issue #369 for `elasticstack_fleet_output`.

## To reproduce

Attempt to import `elasticstack_fleet_agent_policy`.

## Expected behavior

Object should import.

## Version

 - OS: macos
 - Terraform Version: 1.5.4, 1.5.7
 - Provider version: 0.6.2, 0.7.0, 0.8.0
 - Elasticsearch Version: 8.9.0, 8.10.0, 8.10.2

### PR DESCRIPTION
**Pull request by taylor-swanson**
- Fixed fleet objects not having an ID set when importing.
- When creating a new resource, if the ID was not explicitly specified, then the `*_id` value is used from the schema. For all other modes (update, read, delete), the existing/provided ID is used. This resolves the issue where the `*_id` value (even if it was empty) would override the provided ID value (i.e., during import).
- Update fleet documentation to remove kibana space id. Fleet objects aren't scoped by spaces, but rather use their own IDs.

Related issues:
- Fixes #396
- Fixes #369

### CODE REVIEW

**Comment by taylor-swanson** [comment]
Tested importing agent policy, fleet server host, and output:

```
$ TF_LOG=INFO terraform import elasticstack_fleet_agent_policy.docker_fleet_agent elastic-agent-managed-ep
2023-10-13T14:13:49.507-0500 [INFO]  Terraform version: 1.4.6
2023-10-13T14:13:49.508-0500 [INFO]  Go runtime version: go1.19.6
2023-10-13T14:13:49.508-0500 [INFO]  CLI args: []string{"terraform", "import", "elasticstack_fleet_agent_policy.docker_fleet_agent", "elastic-agent-managed-ep"}
2023-10-13T14:13:49.508-0500 [INFO]  Loading CLI configuration from /Users/tswanson/.terraformrc
2023-10-13T14:13:49.508-0500 [INFO]  CLI command args: []string{"import", "elasticstack_fleet_agent_policy.docker_fleet_agent", "elastic-agent-managed-ep"}
2023-10-13T14:13:49.518-0500 [INFO]  provider: configuring client automatic mTLS
2023-10-13T14:13:49.868-0500 [INFO]  provider.terraform-provider-elasticstack: configuring server automatic mTLS: timestamp=2023-10-13T14:13:49.868-0500
2023-10-13T14:13:49.912-0500 [INFO]  provider: configuring client automatic mTLS
2023-10-13T14:13:49.935-0500 [INFO]  provider.terraform-provider-elasticstack: configuring server automatic mTLS: timestamp=2023-10-13T14:13:49.935-0500
elasticstack_fleet_agent_policy.docker_fleet_agent: Importing from ID "elastic-agent-managed-ep"...
elasticstack_fleet_agent_policy.docker_fleet_agent: Import prepared!
  Prepared elasticstack_fleet_agent_policy for import
elasticstack_fleet_agent_policy.docker_fleet_agent: Refreshing state... [id=elastic-agent-managed-ep]
2023-10-13T14:13:50.051-0500 [WARN]  Provider "registry.terraform.io/hashicorp/elasticstack" produced an unexpected new value for elasticstack_fleet_agent_policy.docker_fleet_agent during refresh.
      - .name: was null, but now cty.StringVal("Elastic-Agent (elastic-package)")
      - .namespace: was null, but now cty.StringVal("default")
      - .monitor_logs: was null, but now cty.True
2023-10-13T14:13:50.052-0500 [INFO]  Writing state output to:

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
                                                                                            
$ TF_LOG=INFO terraform import elasticstack_fleet_server_host.default_host fleet-default-fleet-server-host
2023-10-13T14:14:21.337-0500 [INFO]  Terraform version: 1.4.6
2023-10-13T14:14:21.337-0500 [INFO]  Go runtime version: go1.19.6
2023-10-13T14:14:21.337-0500 [INFO]  CLI args: []string{"terraform", "import", "elasticstack_fleet_server_host.default_host", "fleet-default-fleet-server-host"}
2023-10-13T14:14:21.337-0500 [INFO]  Loading CLI configuration from /Users/tswanson/.terraformrc
2023-10-13T14:14:21.338-0500 [INFO]  CLI command args: []string{"import", "elasticstack_fleet_server_host.default_host", "fleet-default-fleet-server-host"}
2023-10-13T14:14:21.346-0500 [INFO]  provider: configuring client automatic mTLS
2023-10-13T14:14:21.379-0500 [INFO]  provider.terraform-provider-elasticstack: configuring server automatic mTLS: timestamp=2023-10-13T14:14:21.379-0500
2023-10-13T14:14:21.417-0500 [INFO]  provider: configuring client automatic mTLS
2023-10-13T14:14:21.438-0500 [INFO]  provider.terraform-provider-elasticstack: configuring server automatic mTLS: timestamp=2023-10-13T14:14:21.438-0500
elasticstack_fleet_server_host.default_host: Importing from ID "fleet-default-fleet-server-host"...
elasticstack_fleet_server_host.default_host: Import prepared!
  Prepared elasticstack_fleet_server_host for import
elasticstack_fleet_server_host.default_host: Refreshing state... [id=fleet-default-fleet-server-host]
2023-10-13T14:14:21.499-0500 [WARN]  Provider "registry.terraform.io/hashicorp/elasticstack" produced an unexpected new value for elasticstack_fleet_server_host.default_host during refresh.
      - .name: was null, but now cty.StringVal("Default")
      - .default: was null, but now cty.True
      - .hosts: was null, but now cty.ListVal([]cty.Value{cty.StringVal("https://fleet-server:8220")})
2023-10-13T14:14:21.501-0500 [INFO]  Writing state output to:

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

$ TF_LOG=INFO terraform import elasticstack_fleet_output.default_output fleet-default-output              
2023-10-13T14:14:27.709-0500 [INFO]  Terraform version: 1.4.6
2023-10-13T14:14:27.709-0500 [INFO]  Go runtime version: go1.19.6
2023-10-13T14:14:27.709-0500 [INFO]  CLI args: []string{"terraform", "import", "elasticstack_fleet_output.default_output", "fleet-default-output"}
2023-10-13T14:14:27.709-0500 [INFO]  Loading CLI configuration from /Users/tswanson/.terraformrc
2023-10-13T14:14:27.710-0500 [INFO]  CLI command args: []string{"import", "elasticstack_fleet_output.default_output", "fleet-default-output"}
2023-10-13T14:14:27.719-0500 [INFO]  provider: configuring client automatic mTLS
2023-10-13T14:14:27.796-0500 [INFO]  provider.terraform-provider-elasticstack: configuring server automatic mTLS: timestamp=2023-10-13T14:14:27.795-0500
2023-10-13T14:14:27.834-0500 [INFO]  provider: configuring client automatic mTLS
2023-10-13T14:14:27.868-0500 [INFO]  provider.terraform-provider-elasticstack: configuring server automatic mTLS: timestamp=2023-10-13T14:14:27.868-0500
elasticstack_fleet_output.default_output: Importing from ID "fleet-default-output"...
elasticstack_fleet_output.default_output: Import prepared!
  Prepared elasticstack_fleet_output for import
elasticstack_fleet_output.default_output: Refreshing state... [id=fleet-default-output]
2023-10-13T14:14:27.929-0500 [INFO]  Writing state output to:

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

**Comment by taylor-swanson** [comment]
@tobio,

I noticed when testing this that there seem to be some breaking changes around the provider schema, specifically when providing `username` and `password` for the `kibana` or `fleet` sections. This used to work, but not anymore, possibly due to #343?

```tf
provider "elasticstack" {
  fleet {
    endpoint = "https://localhost:5601"
    username = "elastic"
    password = "abcd1234"
    insecure = true
  }
}
```

Yields:

```
│ Error: Invalid Path Expression for Schema
│ 
│   with provider["registry.terraform.io/hashicorp/elasticstack"],
│   on /Users/tswanson/Workarea/terraform/elasticstack/test8/main.tf line 1, in provider "elasticstack":
│    1: provider "elasticstack" {
│ 
│ The Terraform Provider unexpectedly provided a path expression that does not match the current schema. This can happen if the path expression does not correctly follow the schema in structure or types. Please report this to the provider developers.
│ 
│ Path Expression: fleet.0.username
╵

╷
│ Error: Invalid Path Expression for Schema
│ 
│   with provider["registry.terraform.io/hashicorp/elasticstack"],
│   on /Users/tswanson/Workarea/terraform/elasticstack/test8/main.tf line 1, in provider "elasticstack":
│    1: provider "elasticstack" {
│ 
│ The Terraform Provider unexpectedly provided a path expression that does not match the current schema. This can happen if the path expression does not correctly follow the schema in structure or types. Please report this to the provider developers.
│ 
│ Path Expression: fleet.0.password
╵
```
Kibana has the same problem. If I move those to `elasticsearch`, then everything works fine.

Not sure if this was intentional or if you've seen anything with this, yet.

**Review by tobio — APPROVED** [review]
LGTM

**Comment by breml** [comment]
@tobio, @taylor-swanson would it be possible to have a new release including this fix, maybe v0.9.1?

**Comment by taylor-swanson** [comment]
@breml, that's what I was thinking, a v0.9.1 release for this and include #448 as well, which was just merged.

@tobio, would we be able to cut a new release soon? It'd be good to get these bug fixes out before the Protocol 6 work gets merged.

**Comment by tobio** [comment]
Yea, we get these two released. It feels worthwhile waiting for https://github.com/elastic/terraform-provider-elasticstack/pull/454 as well unless you think that one might get delayed?

**Comment by taylor-swanson** [comment]
@tobio, I'll see if I can get the changes turned around for #454. If it takes me more than 24 hours, feel free to cut the v0.9.1 release as is and #454 could go into a v0.9.2 or something equivalent. I mainly don't want to hold up the bug fixes as we have a number of people waiting on them.

**Pull request merged**
