### PR TITLE
Switch to protocol 6

### PR DESCRIPTION
**Pull request by dimuon**

### CODE REVIEW

**Comment by dimuon** [comment]
Kibana SLO tests fail for 8.10.3 - have to investigate.

**Comment by taylor-swanson** [comment]
> Kibana SLO tests fail for 8.10.3 - have to investigate.

As an FYI, I noticed these tests failing in my other PRs (#447 and #448), so don't think they're related to this change, but rather something to do with stack version 8.10.x.

**Review by tobio — COMMENTED** [review]
Code change LGTM. Would be worth a changelog, and an update to the provider docs mentioning TF 1.0+ as a requirement.

**Comment by dimuon** [comment]
@tobio , I addressed your comment, would you mind to approve the PR?

**Review by tobio — DISMISSED** [review]
Lgtm

**Comment by dimuon** [comment]
@tobio , looks like I need your approve one more time - I had to resolve a conflict in CHANGELOG after the 0.10.0 release so your last review was dismissed.

**Review by tobio — APPROVED** [review]
Still lgtm

**Pull request merged**
