### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by tobio**
Bumping versions inline with https://github.com/elastic/terraform-provider-elasticstack/commit/7e3d1129e0c98a218b99887d2a7df9bb18b0b709

### CODE REVIEW

**Review by dimuon — DISMISSED** [review]

**Comment by k-yomo** [comment]
@tobio 
Hi! Do you have ETA when `v0.4.0` is released?

**Comment by tobio** [comment]
I've been waiting to get the role mapping PR included. I'll get this out in the next few days.

**Comment by tobio** [comment]
@dimuon are you able to take another quick look at this after rebasing onto main?

**Review by dimuon — APPROVED** [review]
LGTM

**Comment by RobsonSutton** [comment]
@tobio - It looks like this new version wasn't uplifted on the TF Registry, is a resync potentially required to make this available for use via the registry?

**Comment by RobsonSutton** [comment]
Potentially just a conflict between branch and tag names similar to this? - https://github.com/hashicorp/terraform-plugin-sdk/issues/980 
Sounds like a resync should work if so as the branch has now been deleted 👍

**Comment by tobio** [comment]
Thanks for letting me know @RobsonSutton, our repo permissions aren't correct at the moment, so just getting the right auth for my user so I can fix this up. Sorry for the mixup.

**Pull request merged**
