### PR TITLE
[ISSUE-278] Resolve `pipeline_metadata.version` error

### PR DESCRIPTION
**Pull request by RobsonSutton**
- Raised to resolve - #278 
- **[Breaking Change]** Change type of `pipeline_metadata` to schema.TypeString - This setting throws an error when the pipeline is updated manually, as the subsequent terraform plan cannot handle the version value being of type: float64.
- Update docs to reflect #291 
- Reorder Logstash pipeline tests to match the order they are being checked in

### CODE REVIEW

**Comment by RobsonSutton** [comment]
@tobio - Hey, another small one for when you have a spare min or two 👍 

Unfortunately I couldn't find a way to handle multiple data types in TypeMap... (please do enlighten me if this is possible though!)

Have also just deprecated the field as opposed to introducing a breaking change by replacing, so technically the error still exists in the old `pipeline_settings`, but this should provide a workaround for those that may run into it until the older field is fully removed

**Comment by tobio** [comment]
> I'm inclined to just make this a breaking change.

@RobsonSutton, lets do this. It's nicer to break this now and completely close of this bug.

**Comment by RobsonSutton** [comment]
@tobio - Should be updated to be a breaking change now 👍

**Review by tobio — APPROVED** [review]
LGTM  🎉 thanks for tidying this code up :)

**Pull request merged**
