### PR TITLE
Add ca_data field to provider schema

### LINKED ISSUE #110: Allow ca_file raw content in addition to filepath[Feature]
**Is your feature request related to a problem? Please describe.**
I am using terraform_k8s_provider and have my CA certificated stored as secret. I want to be able to pass it to provider using: 
` kubernetes_secret.es_ca.data["ca.crt"]`

**Describe the resource you would like to have implemented.**
Another option to pass the ca certificate to provider

**Describe the solution you'd like**
```

provider "elasticstack" {
  elasticsearch {
    username  = "elastic"
    password  = "changeme"
    endpoints = ["http://localhost:9200"]
   ca_data = [base64 representation of the ca]
  }
}

```

**Describe alternatives you've considered**

For now, I am using insecure = true

### PR DESCRIPTION
**Pull request by k-yomo**
Resolves #110

### CODE REVIEW

**Comment by tobio** [comment]
jenkins test this

**Comment by k-yomo** [comment]
@tobio 
Could you re-run the tests?🙏

**Comment by tobio** [comment]
jenkins test this

**Review by tobio — COMMENTED** [review]
Looking good, can we add a change log entry too please

**Comment by k-yomo** [comment]
@tobio Added change log entry!

**Review by tobio — APPROVED** [review]

**Pull request merged**
