### PR TITLE
feat: use ApiKey instead of Bearer

### PR DESCRIPTION
**Pull request by xeivieni**
as this part of the documentation says https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html

### CODE REVIEW

**Comment by xeivieni** [comment]
@tobio could you please look at this ? 

It fixes bug #415

**Comment by tobio** [comment]
FWIW the correct link for the Kibana API is [here](https://www.elastic.co/guide/en/kibana/current/api.html#api-authentication). It's lacking some detail on how to use API key auth though. The conclusion is however still correct, i.e we need to use the `ApiKey` prefix, rather than `Bearer`. 

The docs linked to in the original issue are for the ESS (Cloud) API which currently uses a different API key to Kibana/Elasticsearch.

**Comment by tobio** [comment]
@xeivieni thanks for taking the time to fix this issue. Are you able to add an item to the [CHANGELOG](https://github.com/elastic/terraform-provider-elasticstack/blob/main/CHANGELOG.md) for this one?

**Review by tobio — APPROVED** [review]
Change LGTM, we just need a changelog entry prior to merging.

**Comment by xeivieni** [comment]
@tobio thanks for the review, I add the information in the CHANGELOG as requested

**Review by tobio — APPROVED** [review]

**Comment by tobio** [comment]
Love it @xeivieni tyvm!

**Comment by xeivieni** [comment]
Do you think it can be released today ?

**Comment by tobio** [comment]
@xeivieni this has been released today as part of 0.11.2

**Pull request merged**
